# Generated by Django 3.1.4 on 2021-03-18 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('miniblog', '0002_post_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='slug',
        ),
    ]
