# Generated by Django 3.1.4 on 2021-03-18 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miniblog', '0003_remove_post_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='data',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='post',
            name='photo',
            field=models.ImageField(upload_to='media/post_photo'),
        ),
    ]
