# Generated by Django 3.1.4 on 2021-03-18 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miniblog', '0006_auto_20210318_2321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='data',
            field=models.TextField(blank=True, null=True),
        ),
    ]
