# Generated by Django 3.1.4 on 2021-03-18 22:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('miniblog', '0009_auto_20210319_0020'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='owner',
            new_name='user',
        ),
    ]
